# fly.toml app configuration file generated for scriptmaker on 2023-10-20T22:17:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scriptmaker"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
